---
title: "table1"
author: "Andrew Mertens"
date: "10/24/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo=F, warning=F}
library(here)
library(tidyverse)
library(table1)

load(here("data/analysis_dataset.Rdata"))

df <- d %>% filter(sample==1)

Wvars=c("rent_own", "Gender", "Race", "Ethnicity", "Age", "Education", "native_plant", "convinceOther")

table1(~ rent_own+ Gender+ Race+ Ethnicity+ Age+ Education+ native_plant+ convinceOther | tr, data=df)

```


## check if mean covariates differ between samples 1 or 2 for individuals with selftimesused =1
```{r, echo=F, warning=F}
df <- d %>% filter(selftimesused==1)

table1(~ rent_own+ Gender+ Race+ Ethnicity+ Age+ Education+ native_plant+ convinceOther | sample, data=df)

```


## check if mean covariates differ between samples 1 or 2 for individuals with friendused =1

```{r, echo=F, warning=F}
df <- d %>% filter(friendtimesused==1)

table1(~ rent_own+ Gender+ Race+ Ethnicity+ Age+ Education+ native_plant+ convinceOther | sample, data=df)

```